// Pinned community browser port of Kyutai Pocket TTS, using its Alba voice.
const model = {
  name: 'Pocket TTS',
  adapter: './models/pocket.js?v=1',
  repository: 'ekzhang/jax-js-models',
  revision: '2b0fc51b4f76ff56611741ab9267593decde7639',
  weightsFile: 'kyutai-pocket-tts_b6369a24-fp16.safetensors',
  weightsBytes: 235738516,
  voiceRepository: 'kyutai/pocket-tts-without-voice-cloning',
  voiceRevision: 'fbf82802feb1f92664f3bcf6a0f01295a678853c',
  voicesFile: 'embeddings/alba.safetensors',
  tokenizerFile: 'tokenizer.model',
  voice: 'Alba',
  sourceRevision: '970fa22d934ce2e617cd3a993c6ecc8b736496f2',
  tokenLimit: 256,
  downloadMB: 237,
  synthesisRates: Object.freeze([1]),
  defaultRate: 1,
  backend: 'wasm',
  backendLabel: 'CPU · WASM',
  dtype: 'float32',
  seed: 42,
};
export const MODEL = Object.freeze({ ...model,
  id: [model.adapter, model.repository, model.revision, model.weightsFile,
    model.voiceRepository, model.voiceRevision, model.voicesFile, model.tokenizerFile,
    model.sourceRevision, model.voice, model.tokenLimit, model.defaultRate,
    model.backend, model.dtype, model.seed].join('|'),
});
